server:
  port: 8080

#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: 123456

spring:
  h2:
    console:
      path: /h2-console #进入h2 web操作界面的路径
      enabled: true #开启h2 web界面
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db_test;MODE=MYSQL;IGNORECASE=TRUE;AUTO_SERVER=TRUE
    #url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL # 仍然使用mysql模式是为了从h2切换到mysql时完全兼容
    username: root
    password: 123456
#  sql:
#    init:
#      schema-locations: classpath:db/schema.sql
#      data-locations: classpath:db/data.sql
#      mode: embedded

mybatis:
  mapper-locations: classpath*:mybatis/**/Mysql_*Mapper.xml