server:
  port: 8080

graphql:
  servlet:
    enabled: true
    mapping: /v1/graphql
    cors-enabled: true
    cors:
      allowed-origins: http://localhost:8081
      allowed-methods: GET, HEAD, POST