server:
  port: 8080

spring:  
  datasource:
    #type : com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
    url: jdbc:derby:testdb;create=true
    username: root
    password: 123456